**SINTAXIS BASICA PYTHON**

In [ ]:
entero = 34-23 #un comentario
cadena = "hola" #otro comentario
decimal = 3.45
if decimal == 3.45 or cadena == "hola":
  entero = entero + 1
  string_ = cadena + "mundo" #concatenacion de string
print(cadena)
print(entero)

hola
12

COMENTARIOS


*   Se debe preceder con el simbolo "#"
*   Tambien se pueden introducir un comentarios con varias lineas poniendo tres comillas """ al inicio y final del mismo.

ESPACION EN BLANCO


*   Los espacion en blanco y los saltos de linea tienen significado "IDENTACION"
*   Un salto de linea marca el final de una sentancia
*   Se usa \ para indicar que una sentencia ocupara varias lineas.
*   La primer linea con un nivel mayor de identacion especifica el comienzo de un bloque
*   La primer linea con un nivel menor de identacion especifica el fin de un bloque

In [ ]:
variable_1 = 10 #fin de sentencia con el el salto de renglon  
variable_2 = "soy una asignacion"
if variable_1 == 10:
  variable_1 = 15         # Mayor identacion indica inicio de un bloque
  variable_2 = "yo no lo soy"
print (variable_2)        #Menor identacion indica un fin de bloque

yo no lo soy

### VARIABLES

*   Nombre que se le da a un valor u objeto
*   Su nombre puede contener :
    * Caracateres alfanumericos; a-z, A-Z, 0-9
    * Guion bajo _ 
* No se pueden utilizar ciertas palabras reservadas ;
    * ans, as, assert, class, continue, def, del, elif, else, except, exec, finally, for, from, global, it, import, is, in, lamba, not, or, pass, print, raise, return, try, while, with, yield.
* para buensa practicas
    * Las funciones deben iniciar con minusculas
    * Deben ser autoexplicativos que nos ayuden a entender el codigo

In [ ]:
cod_contrato = "213546646515" #ejemplo de una buena practica

INPUT
*   Para introducir valores se utiliza la funcion de input()

In [ ]:
entrada = input("ingrese cualquier cosa que quiera")
print("Has introducido: " + entrada)

ingrese cualquier cosa que quieraHola
Has introducido: Hola

OUTPUT
* Para mostrar cualquier valor o resultado en pantalla se utiliza la funcion print( )

In [ ]:
print("Esto es una prueba")
cod_contrato = "5464846546546846218"
print(cod_contrato)

Esto es una prueba
5464846546546846218

TIPOS DE DATOS
* String (cadena de texto) se especifica entre comillas simples, dobles o triples
* Int (enteros) no incluye punto decimal
* Float (decimales) incluye punto decimal
* Bool (boleanos) true/false
Para saber el tipo de una variable se utiliza la funcion type( )

![image.png]()

In [ ]:
cadena = "esto es un cadena de texto"
entero = 52
decimal = 52.28
boleano = True

print(type(cadena))
print(type(entero))
print(type(decimal))
print(type(boleano))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

Modificacion de los tipos 
* Se puede modificar explicitamente el tipo de dato de una variable
* Para ello se utiliza las funciones: srt, int, float, bool.
No todas aplican para realizar dicho cambio

In [ ]:
print(str(entero))
print(int(decimal))
print(float(boleano))
print(float(cadena))

52
52
1.0

ValueError: ignored

VALOR NULO
* Para crear una variable con valor nulo, se le asigna la palabra None
* Util para eliminar referencias o para que se libere memoria

In [ ]:
vacio = None
print(vacio)
print(type(vacio))

None
<class 'NoneType'>

### OPERADORES BASICOS 
* ARITMETICOS: +, -, /, *, **, %, //
* LOGICOS: and, or, not
* COMPARATIVOS: ==, !=, ><, <=, >=
* ASIGNACION: =, +=, -=, *=, /=, **=, %=,

In [ ]:
#ARITMETICOS
a = 5+5
b = 5-9
c = 5/5
d = 96*1

In [ ]:
#COMPARATIVOS
b = 4
print ( a > b)
print ( a != b)
print ( a < b)
print ( a == b)

True
True
False
False

In [ ]:
#LOGICOS
a = 3
a > 2 and a > 6

False

In [ ]:
a > 2 or a < 0

True

In [ ]:
not a > 2

False

In [ ]:
#ASIGNACION
a += 8
a

11

### ESTRUCTURA DE DATOS
* Secuencias 
* Diccionarios
* Conjuntos

SECUENCIAS

Es un listado unidimesnional y ordenados de valores que pueden ser de cualquier tipo, incluso otro de estructuras de datos anidadas. Existen tres tipos bien diferenciados:
  * Tuplas:listados inmutables
  * Listas: listados ordenados mutables
  * Cadenas de caracteres: inmutables y cuyos elementos son siempre caracteres
Casi todas la operaciones se pueden aplicar a cualquier tipo de secuencia exceptuando las que implican modificacion, que solo aplican para las listas

CREACION DE SECUENCIAS

In [ ]:
#EN PYTHON LA INDEXACION COMIENZA CON EL NUMERO 0
lista = [1, 2, 3, 4, "a", "b"]
tupla = (1, 2, 3, 4, "a", "b")
str1 = "los strings son una secuencia de carateres"

#PARA LLAMAR UN ELEMENTO
lista[0]
tupla[0]
str1[8]
#PARA MODIFICAR UN VALOR, PONER LA POSICION DEL VALOR A MODIFICAR
lista[5] = 20
#str1[8] = "z" #las cadenas de texto son inmutables

CONVERCION ENTRE TIPOS DE ESTRUCTURAS

In [ ]:
lista = [1, 2, 3, 4, "a", "b"]
tupla = (1, 2, 3, 4, "a", "b")
str1 = "los strings son una secuencia de carateres"

tupla2 = tuple(lista)
lista2 = list(tupla)
tupla3 = tuple(str1)

print(tupla2)
print(lista2)
print(tupla3)

(1, 2, 3, 4, 'a', 'b')
[1, 2, 3, 4, 'a', 'b']
('l', 'o', 's', ' ', 's', 't', 'r', 'i', 'n', 'g', 's', ' ', 's', 'o', 'n', ' ', 'u', 'n', 'a', ' ', 's', 'e', 'c', 'u', 'e', 'n', 'c', 'i', 'a', ' ', 'd', 'e', ' ', 'c', 'a', 'r', 'a', 't', 'e', 'r', 'e', 's')

CREACION DE SECUENCIAS ANIDADAS

In [ ]:
tupla = (1, 2, 3, 4, "a", "b", [20, 5, 9, 45, "t", "k"])
lista = [1, 2, 3, 4, "a", "b", (0, 9, 8, 6, "y", "q",)]

print(tupla)
print(lista)

(1, 2, 3, 4, 'a', 'b', [20, 5, 9, 45, 't', 'k'])
[1, 2, 3, 4, 'a', 'b', (0, 9, 8, 6, 'y', 'q')]

CONCATENACION DE SECUENCIAS

In [ ]:
lista1 = [1, 2, 3, 4, "a", "b"]
tupla1 = (1, 2, 3, 4, "a", "b")
str1 = "los strings son una secuencia de carateres"

lista2 = [8, 6, 7, 9, "F", "D"]
tupla2 = (8, 6, 7, 9, "W", "Q")
str2 = "ESTO ES OTRA SECUENCIA DE CARACTERES"

lista3 = lista1 + lista2
tupla3 = tupla1 + tupla2
str3 = str1 + str2

print(lista3)
print(tupla3)
print(str3)

[1, 2, 3, 4, 'a', 'b', 8, 6, 7, 9, 'F', 'D']
(1, 2, 3, 4, 'a', 'b', 8, 6, 7, 9, 'W', 'Q')
los strings son una secuencia de carateresESTO ES OTRA SECUENCIA DE CARACTERES

MULTIPLICACION DE SECUENCIAS POR ENTEROS

In [ ]:
lista1 = [1, 2, 3, 4, "a", "b"]
listadoble = lista1 * 5

tupla2 = (8, 6, 7, 9, "W", "Q")
tupladoble = tupla2 *4

str2 = "ESTO ES OTRA SECUENCIA DE CARACTERES"
strdoble = str2 * 3

print(listadoble)
print(tupladoble)
print(strdoble)

[1, 2, 3, 4, 'a', 'b', 1, 2, 3, 4, 'a', 'b', 1, 2, 3, 4, 'a', 'b', 1, 2, 3, 4, 'a', 'b', 1, 2, 3, 4, 'a', 'b']
(8, 6, 7, 9, 'W', 'Q', 8, 6, 7, 9, 'W', 'Q', 8, 6, 7, 9, 'W', 'Q', 8, 6, 7, 9, 'W', 'Q')
ESTO ES OTRA SECUENCIA DE CARACTERESESTO ES OTRA SECUENCIA DE CARACTERESESTO ES OTRA SECUENCIA DE CARACTERES

Comprobar si un elemento existe en la Secuencia

In [ ]:
lista1 = [1, 2, 3, 4, "a", "b"]
tupla1 = (1, 2, 3, 4, "a", "b")
str1 = "los strings son una secuencia de carateres"

print(4 in lista1)
print(5 not in tupla1)
print(4 in tupla1)
print(5 not in lista1)
print("a" in str1)
print("z" not in str1)

True
True
True
True
True
True

Acceder un a un elemento de la Secuencia

In [ ]:
#INDEXACION POSTIVA
lista1 = [1, 2, 3, 4, "a", "b"]
tupla1 = (1, 2, 3, 4, "a", "b")
str1 = "los strings son una secuencia de carateres"

print(tupla[4])
print(lista[5])
print(str1[20])

#INDEXACION NEGATIVA

print(tupla[-3])
print(lista[-4])
print(str1[-15])

a
b
s
a
4
i

SLICING DE SECUENCIAS (PARTES DE UN ESTRUCTURA DE DATOS)
* Seleccion de un conjunto de elementos ordenados que pertenecen a una secuencia
* Se realiza mediante la notacion secuencial [inicio:termino:orden]
  * Inicio: indica el termino de donde se parte la extraccion (base 0). SI SE OMITE SE TOMA EL 0 COMO PARAMETRO
  * Termino: indica el termino de donde se finaliza la extraccion, la extraccion se realiza siempre menos un termino (base -1). SI SE OMITE EXTRAE HASTA EL ULTIMO TERMINO
  * Orden: tamaño del salto en que se realiza la extraccion. si se omite se toma el 1 como parametro

In [ ]:
lista1 = [1, 2, 3, 4, "a", "b"]
tupla1 = (1, 2, 3, 4, "a", "b")
tupla_nombres = ("uno", "dos", "tres", "cuatro", "letra a", "letra b")
str1 = "los strings son una secuencia de carateres"

print(tupla[0:4:1])
print(lista[0:4:2])
print(str1[5:20])
print(tupla[:4:2])
print(lista[0:])
print(str1[1:15:2])

# LONGITUD DE SECUENCIAS    len
print(len(lista1))
print(len(tupla1))
print(len(str1))

#OBTENCION DEL INDICE EN QUE APARECE UN ELEMENTO POR PRIMERA VEZ      index
print(lista1.index(2))
print(tupla1.index(1))
print(str1.index("t"))

#OBTERNER EL NUMER DE VECES QUE SE REPITE UN ELEMENTO       count
print(lista1.count(2))
print(tupla1.count(1))
print(str1.count("t"))

#ASIGNACION DE VARIABLES A CADA ELEMENTO DE UNA SECUENCIAS
var1, var2, var3, var4, var5, var6 = tupla1
print(var1)
print(var2)
print(var3)
print(var4)
print(var5)
print(var6)

# UNION DE SECUENCIAS ORDENADAMENTE
tupla_lista = zip(tupla_nombres, lista1)
print(list(tupla_lista))

(1, 2, 3, 4)
[1, 3]
trings son una
(1, 3)
[1, 2, 3, 4, 'a', 'b', (0, 9, 8, 6, 'y', 'q')]
o tig o
6
6
42
1
0
5
1
1
2
1
2
3
4
a
b
[('uno', 1), ('dos', 2), ('tres', 3), ('cuatro', 4), ('letra a', 'a'), ('letra b', 'b')]

CREACION DE SECUENCIAS NUMERICAS

In [ ]:
# Se sigue la misma logica de las estructuras de datos  [inicio, final, tamaño]

secuencia = range(10)
print(secuencia)
print(list(secuencia))

secuencia2 = range(0,100,5) #De cero a cien de 5 en 5
print(secuencia2)
print(list(secuencia2))

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
range(0, 100, 5)
[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

AGREGAR ELEMENTOS A UNA LISTA (por el final)

In [ ]:
lista_num = ["uno", "dos"]
lista_num.append("tres") #Escribir el nombre de variable, la fucnion y el valor que se quiere agregar
print(lista_num)

['uno', 'dos', 'tres']

INSERTAR ELEMENTOS EN UNA POSICION ESPECIFICA DE UNA LISTA

In [ ]:
lista_num = ["dos", "tres"]
lista_num.insert(0, "uno") # Escribir el nombre de la variable, la funcion, la posicion que queremos ocupar y el valor del elemento
print(lista_num)

['uno', 'dos', 'tres']

ASIGNACION DE VALORES A UN SLICE (listas)

In [ ]:
lista_1 = [1, 2, 3, 4, "a", "b"]
lista_1[2:4] = [6,7] # nombre de la variable, entre que numeros quieres agregar y el valor para cada uno de los elemntos a agregar
print(lista_1)

lista1 = [1, 2, 3, 4, "a", "b"]
lista1[2:6] = [6] #si los valores no son suficientes para llenar los espacion, los deja en blanco y se reduce la lista
print(lista1)


# RECUPERACION  Y ELIMINACION DE UN ELEMENTO
lista1 = [1, 2, 3, 4, "a", "b"]
print(lista1.pop(3)) # escribir la posicion del elemento a eleminar
print(lista1) #la funcion la podemos 

# ELIMINACION DEL PRIMER ELEMENTO COINCIDIENTE
lista_uno = [[7, 4], 4, 9, "s", "t"]
lista_uno.remove(4) # eliminacion x valor
print(lista_uno)

# ELIMINACION DE ELEMENTOS (eliminacion x posicion)
lista_dos = [1, 2, 3, 4, "a", "b"]
del lista_dos[2] # se pone el lugar del valor a eliminar. 
print(lista_dos)

# ORDENACION DE ELEMENTOS
lista_tres = [77, 26, 35, 48, 0, 50]
lista_tres.sort() 
print(lista_tres)

lista_tres.sort(reverse=True) #orden inverso 
print(lista_tres)

#RECUPERACION INVERSA DE ELENTOS
lista_3 = [1, 6, 9, 4, 5, 7]
lista_3.reverse() # le da vuelta a la lista, de final a inicio
print(lista_3)

[1, 2, 6, 7, 'a', 'b']
[1, 2, 6]
4
[1, 2, 3, 'a', 'b']
[[7, 4], 9, 's', 't']
[1, 2, 4, 'a', 'b']
[0, 26, 35, 48, 50, 77]
[77, 50, 48, 35, 26, 0]
[7, 5, 4, 9, 6, 1]

FUSIONAR LISTAS

In [ ]:
a = [25, 58, 56, 98, 20, 34, 77, 65, 26]
b = [55, 48, 61, 22, 39, 37, 86, 40, 99]
a.extend(b) #se modifica la lista "a" al agregar los elementos de "b"
print(a)

#otra manera es
c = [25, 58, 56, 98, 20, 34, 77, 65, 26]
d = [55, 48, 61, 22, 39, 37, 86, 40, 99]
suma_cd = c + d # aqui ninguna de las listas se modifica, se crea una variable nueva
suma_cd

[25, 58, 56, 98, 20, 34, 77, 65, 26, 55, 48, 61, 22, 39, 37, 86, 40, 99]

[25, 58, 56, 98, 20, 34, 77, 65, 26, 55, 48, 61, 22, 39, 37, 86, 40, 99]

CONVERTIR DE MAY A MIS (VICEVERSA)

In [ ]:
str_1 = "LAS CADENAS DE CARACTERES SON TAMBIEN UNA SECUENCIA"
print(str_1.lower())
str_2 = "las cadenas de caracteres son tambien una secuencia"
print(str_2.upper())

#SEGMENTACION POR CARACTERES
str_2 = "las cadenas de caracteres son tambien una secuencia"
print(str_2.split(" "))

#REEMPLAZO DE CADENAS
str_2 = "LAS CADENAS DE CARACTERES SON TAMBIEN UNA SECUENCIA UNA"
print(str_2.replace("UNA", "OTRA")) # cuando no especificas, cambia todas las palabras
print(str_2.replace("UNA", "OTRA", 1)) #es necesario poner la palabra a buscar, la que vamos a poner y la poscion

las cadenas de caracteres son tambien una secuencia
LAS CADENAS DE CARACTERES SON TAMBIEN UNA SECUENCIA
['las', 'cadenas', 'de', 'caracteres', 'son', 'tambien', 'una', 'secuencia']
LAS CADENAS DE CARACTERES SON TAMBIEN OTRA SECUENCIA OTRA
LAS CADENAS DE CARACTERES SON TAMBIEN OTRA SECUENCIA UNA

### DICCIONARIOS

* Es una estructura que:
  * Contiene un listado de pares (clave;valor)
  * Sin orden
  * Tambien se le llama array o hash map
  * Las claves son cadenas o valores numericos
  * Los valores pueden ser valores numericos o secuencias anidadas

In [ ]:
dict_1 = {"clave uno": 1, "clave dos": 2}
print(dict_1)

dict_2 = {10:1, 2:2}
print(dict_2)

# CREACION DE DICCIONARIOS ANIDADOS
dict_anidado = {"clave_1": 1, "clave_2": {"clave_21":[5, 2, 8, 6], "clave_22": 5, }}
print(dict_anidado)

# CREACION DE DICCIONARIOS DESDE TUPLAS Y LISTAS (CLAVE- VALOR)
tupla_ = (1, 2, 3, 4, 5, 6)
lista_ = ["unos", "dos", "tres", "cuatro", "cinco", "seis"]
dic_union = dict(zip(lista_, tupla_))
print(dic_union)

UNION DE DOS DICCIONARIOS

In [ ]:
dict1 = {"clave uno": 1, "clave dos": 2}
dict2 = {"clave tres": 3, "clave cuatro": 4}
dict1.update(dict2)
print(dict1) # EL diccionario 2 queda intacto pero el diccionario 1 se modifica

# INSERCION O MODIFICACION DE UN ELEMENTO POR CLAVE
dict_UNO = {"clave uno": 1, "clave dos": 2}
dict_UNO["clave tres"] = "prueba"  # para agregar un elemento nombre del diccionario, la clave y el nuevo valor
dict_UNO["clave dos"] = 5  #para modificar el valor de una elemento
print(dict_UNO)

# RECUPERACION Y ELIMINACION DE UN ELEMENTO DE UNA CLAVE ESPECIFICA
dict_DOS = {"clave uno": 1, "clave dos": 2}
clavedos = dict_DOS.pop("clave dos") # nombre del diccionario, la funcion"pop" y la clave del elemento
print(clavedos) # el valor eliminado se guardad en la var clavedos

# COMPROBACION DE UN ELEMENTO DENTRO DEL DICCIONARIO
dict_TRES = {"clave uno": 1, "clave dos": 2}
print("clave uno" in dict_TRES) # el nombre de la clave, "in" y el nombre del diccionario
print(1 in dict_TRES) # O el valor, "in" y el nombre del diccionario

# ELIMINACION DE UN ELEMENTO EN EL DICCIONARIO
dict_CUATRO = {"clave uno": 1, "clave dos": 2}
del dict_CUATRO["clave uno"] # funcion "del",  el nombre del diccionario y la clave
print(dict_CUATRO)

# ELIMINACION DE TODOS ELEMENTOS DE UN DICCIONARIO
dict_CINCO = {"clave uno": 1, "clave dos": 2}
dict_CINCO.clear() # el nombre del diccionario y funcion "clear",  
print(dict_CINCO)

# ACCESO A UN ELEMENTO POR CLAVE
dict_SEIS = {"clave uno": 1, "clave dos": 2}
print(dict_SEIS["clave dos"])  # poner el nombre deL diccionario y la clave del valor que necesitamos

# RECUPERACION DE ELEMNTOS COMO LISTA
dict_SIETE = {"clave uno": 1, "clave dos": 2}
print(list(dict_SIETE.items())) # el nombre del diccionario y funcion "clear", 

# RECUPERACION DE CLAVES COMO LISTA
dict_OCHO = {"clave uno": 1, "clave dos": 2}
print(list(dict_OCHO.keys()) # el nombre del diccionario y funcion "clear",  
      
# RECUPERACION DE VALORES COMO LISTA
dict_NUEVE = {"clave uno": 1, "clave dos": 2}
print(list(dict_NUEVE.values())

### CONJUNTOS

* Unidimensional (de un unico nivel), ya no existen las claves
* Mutable
* De tamaño variable (al ser mutable es obvio)
* Desordenada
* Cuyos elementos son valores o secuencias
* Cuyos elementos son unicos (no hay elemento repertidos)

In [ ]:
set1 = {1, 2, 3, 4, 5, 6}
print(set1)

#CONVERSION DE UN CONJUNTO
lista_UNO =[1, 2, 3, 4, 5, 6]
setuno = set(lista_UNO)
print(type(setuno))

#UNION DE DOS CONJUNTOS
set1 = {1, 2, 3, 4, 5, 6}
set2 = {6, 2, 8, 11, 5, 9}
print(set1 | set2)

#INTERSECCION DE DOS CONJUNTOS
set1 = {1, 2, 3, 4, 5, 6}
set2 = {6, 2, 8, 11, 5, 9}
print(set1 & set2)

#DIFERENCIA DE DOS CONJUNTOS
set1 = {1, 2, 3, 4, 5, 6}
set2 = {6, 2, 8, 11, 5, 9}
print(set1 - set2)

#DIFERENECIA SIMETRICA DE DOS CONJUNTOS
set1 = {1, 2, 3, 4, 5, 6}
set2 = {6, 2, 8, 11, 5, 9}
print(set1 ^ set2)

# INSERCION O MODIFICACION DE UN ELEMENTO POR CLAVE
set1 = {1, 2, 3, 4, 5, 6}
set1.add(7) # nombre del conjunto, la funcion "add" y el valor que se quiere agregar
print(set1)

# COMPROBACION DE UN ELEMENTO DENTRO DEL DICCIONARIO
set1 = {1, 2, 3, 4, 5, 6}
1 in set1 # el valor que queremos comprobar, "in" y el nombre del conjunto

# COMPROBACION DE UN SUBCONJUNTO DEL DICCIONARIO
set1 = {1, 2, 3, 4, 5, 6}
set3 = {1, 2, 3}
set1 >= set3 # ponemos el nombre del conjunto mayor y depues el nombre del subconjunto

# COMPROBACION DE UN SUPERCONJUNTO DEL DICCIONARIO
set1 = {1, 2, 3, 4, 5, 6}
set3 = {1, 2, 3}
set1 <= set3 # ponemos el nombre del superconjunto mayor y depues el nombre del conjunto

# ELIMINACION DE UN ELEMENTO POR SU VALOR
set_DOS = {1, 2, 3, 4, 5, 6}
set_DOS.remove(5) # funcion "del",  el nombre del conjunto y su valor
print(set_DOS)

set_DOS = {1, 2, 3, 4, 5, 6}
set_DOS.discard(9) # cuando no estamos seguro de que exista utilizamos esta funcion, si no existe no pasa nada 
print(set_DOS)

# ELIMINACION DE TODOS ELEMENTOS DE UN CONUNTO
set1 = {1, 2, 3, 4, 5, 6}
set1.clear() # el nombre del conjunto y funcion "clear",  
print(set1)

### ESTRUCTURAS DE CONTROL

Las estructuras de control de flujo nos permiten la construccion de programas. Estas estructuras son identicos en funcionamiento al resto de los lenguajes de programacion.

CONDICIONALES (if, elif, else)
* Estas estructuras de control nos permiten elegir, en base a una condicion dada, la ejecucuion de diferentes bloques de codigo.

In [ ]:
precio_taxi = 10
precio_bus = 2.5
dinero_disponible = 1.5

In [ ]:
# Esta forma de realizar la condicionante es muy reduntante y obliga a las condiciones bastantes complejas

if precio_taxi < dinero_disponible:
  print("Me voy en taxi")
if precio_bus < precio_bus and precio_taxi > dinero_disponible:
  print("Me voy en bus")
if precio_bus > dinero_disponible:
  print("Me voy andando")

# Una forma de reescribir es
if precio_taxi < dinero_disponible:
  print("Me voy en taxi")
elif precio_bus < dinero_disponible:
  print("Me voy en bus")
else:
  print("Me voy andando")

Me voy andando
Me voy andando

BUCLE - for
* Estas estructuras de control nos permiten llevar a cabo la ejecucion de un bloque de codigo para todos los elementos condenidos en una secuencia donde pueden estar involucrados o no el bloque de codigo.

In [ ]:
for i in range(0, 10):
  print("Hola Mundo")

for i in range(0, 10):
  print("Hola Mundo: " + str(i))

lista_b = ["uno", "dos", "tres", "cuatro", "cinco", "seis"]
for element in lista_b: # para cada elemento de mi lis x 
  print(element)         # imprimir el elemento

#A veces es muy comodo disponer al mismo tiempo del elemento sobre el que se itera y el indice que ocupa dentro del bucle. 
# Para ello podemos utiliza "in" funcion "enumarte"

lista_b = ["uno", "dos", "tres", "cuatro", "cinco", "seis"]
for index, element in enumerate(lista_b): # index es la poscicion en la que me encuentro y enumerate trabaja con los valores de la lista
  print("Elemento en indice " + str(index) + " : " + element) #imprime la posicion : mas el elemento en la lista correspondiente

Hola Mundo
Hola Mundo
Hola Mundo
Hola Mundo
Hola Mundo
Hola Mundo
Hola Mundo
Hola Mundo
Hola Mundo
Hola Mundo
Hola Mundo: 0
Hola Mundo: 1
Hola Mundo: 2
Hola Mundo: 3
Hola Mundo: 4
Hola Mundo: 5
Hola Mundo: 6
Hola Mundo: 7
Hola Mundo: 8
Hola Mundo: 9
uno
dos
tres
cuatro
cinco
seis
Elemento en indice 0 : uno
Elemento en indice 1 : dos
Elemento en indice 2 : tres
Elemento en indice 3 : cuatro
Elemento en indice 4 : cinco
Elemento en indice 5 : seis

BUCLE - while
* Estas estructuras de control nos permiten llevar a cabo la ejecucion de un bloque de codigo minestras se cumple una condicion dada.

In [ ]:
i = 0 #TIENE UNA VARIABLE
while i < 10: #UNA CONDICION 
  print(i)  # REALIZA LA FUNCION IMPRIMIR HASTA QUE SE MANTENGA LA CONDICION
  i += 1 # LLEVA UNA JERARQUIA

0
1
2
3
4
5
6
7
8
9

INTERRUPCION DE BUCLES (break y continue)
* Las sentencias break y continue permiten ahorrar el flujo normal de ejecuciion de un bucle. Mas concretamentes:
  * Break: Corta completamente el flujo de ejecucion del bucle y pasa el control a la setencia posterior del bucle
  * Continue: Corta la ejecucion de la iteracion actual y pasa el control a la siguiente sentencia del bucle

In [ ]:
lista_COPIA1 = ["uno", "dos", "tres", "cuatro", "cinco", "seis"]
for element in lista_COPIA1:
  if element == "cuatro":
    break  # Lo que hace es generar un corte en el codigo omitiendo los valores d que siguen despues de la condicion
  print(element) #dando por terminada la iteracion

lista_COPIA2 = ["uno", "dos", "tres", "cuatro", "cinco", "seis"]
for element in lista_COPIA2:
  if element == "cuatro":
    continue # Lo que hace es generar un salto en el codigo, omitiendo el valor que cumple con la condicion if
  print(element)

uno
dos
tres
uno
dos
tres
cinco
seis

COMPRENSIONES DE LISTAS
* Tenemos a nuestra disposicion una estrucutra especial de control (semejeante a los bucles) que facilita mucho la escritura de codigo

In [ ]:
lista_M = ["enero", "febrero", "marzo", "abril", "mayo", "junio"]
lista_V = []
for element in lista_M:
  if element[0] == "m": # si elmento incicia con m
    lista_V.append(element.upper()) #agregar a la lista_V pero con mayusculas
print(lista_V)

# PODEMOS CONSEGUIR EL MISMO RESULTA CON UN CODIGO MAS CONCISO Y DE FORMA MAS RAPIDO
lista_M = ["enero", "febrero", "marzo", "abril", "mayo", "junio"]
lista_V = [element.upper() for element in lista_M if element[0] == "m"] 
#carcateristica con la cual se va agregar "upper", el bucle "for" y la condicion que tiene que cumplir para añada "if"
print(lista_V)

['MARZO', 'MAYO']
['MARZO', 'MAYO']

OTRAS COMPRESIONES
* Del mimso modo, se puede utilizar la sitaxis de las compresiones de listas para crear otras estrucutras con diccionarios y conjuntos

In [ ]:
{element.upper(): element[0] == "m" for element in lista_M}  #PODEMOS HACER LOS MISMO PARA LOS DICCIONARIOS

{'ABRIL': False,
 'ENERO': False,
 'FEBRERO': False,
 'JUNIO': False,
 'MARZO': True,
 'MAYO': True}

In [ ]:
lista_MESES = ["enero", "febrero", "marzo", "abril", "mayo", "junio", "mayo"]
{element for element in lista_MESES} # Y TAMBIEN APLICA PARA LOS CONJUNTO, CUANDO QUEREMOS ELIMINAR DUPLICADOS

{'abril', 'enero', 'febrero', 'junio', 'marzo', 'mayo'}

  CONTRO DE ERRORES/EXCEPCIONES (try, expcet, finally)

  Los errores se generan en forma de excepciones (objetos en los que se incluye tanto el detalle del error y la fila de codigo. Es importante realizar una buena gestion de excepciones de forma que los errores esten siempre controlados de forma que los progrmaas sean robustos y claros:

In [ ]:
# ESTO ES IMPORTANTE POR QUE HAY VECES QUE QUEREMOS QUE LE CODIGO SIGA CORRIENTO, AUNQUE SE GENEREN ERRORES
# LOS CUALES PODEMOS IDENTIFICAR AL FINAL DE CADA BLOQUE
cadena_1 = "12.52cadena"
entero_1 = float(cadena_1)

ValueError: ignored

In [ ]:
# SE PUEDEN CONTROLAR TODOS LOS ERRORES DE MANERA GENERICA
try: # dentro de la identacion se excribe el codigo que queremos correr
  cadena_1 = "cadena"
  entero_1 = float(cadena_1)
except: # dentro de este bloque se pone las medidas que se deben toma con respecto al error
  print("esto es un error")

# PUEDE SER MAS DETALLADO
try:
  cadena_1 = "cadena"
  entero_1 = float(cadena_1)
except Exception as e: # la funcion exception nos indica cual es el error
  print(e)
  print("esto es un error")

In [ ]:
# O SE PUEDE REALIZAR UN CONTROL DETALLADO PARA CADA ENTRADA
try:
  cadena_1 = "cadena"
  entero_1 = float(cadena_1)
except RuntimeError as e: # ERROR A MITAD DE CORRER EL CODIGO
  print(e)
  print("esto es un error")
except ValueError as e: #EL FORMATO DEL VALOR NO ES CORRECTO 
  print(e)
  print("esto es un error")
except Exception as e: # FORMATO GENERICO
  print(e)
  print("esto es un error")

In [ ]:
try:
  cadena_1 = "cadena"
  entero_1 = float(cadena_1)
except: 
  print("esto es un error")
finally:
  cadena_1 += " adios"

### FUNCIONES
* Pueden entenderse como un nombre asignado a un bloque de codigo que permite su posterior invocacion 
* Dispone de un conjunto de parametros de entradas (opcinales) sobre los que trabajara el bloque de codigo interno.
* Ofrecen un resultado de de salida (opcinal) que podra ser utilizado por el codigo que invoca a ala funcion
* Permite encapsular codigo de forma que puede ser reutlizado en varios puntos de un programa.
* Evitan la necesidad de copiar y pegar el codigo.
* Facilita el mantenimiento y reduce los posible puntos de error.
* Permite "generalizar" codigo al trabajar sobre unos parametros de entrada que puden ser "variables".

In [ ]:
lista_W = ["enero", "febrero", "marzo", "abril", "mayo", "junio"]
lista_Z = []
for element in lista_W:
  if element[0] == "m": # si elmento incicia con m
    lista_Z.append(element.upper()) #agregar a la lista_V pero con mayusculas
print(lista_Z)

#SIN AMBARGO CUANDO QUEREMOS REPLICAR EL PROCEDIMIENTO MUCHAS ES CONVENIENTE CREAR UNA FUNCION

def fun_lista (lista, inicial, mayuscula): #def, nombre de la funcion y los parametros o varibles que vamos a ocupar
  lista_out = [] # lista que nos va devolver
  for element in lista: # nombre de la lista que va a analizar
    if element[0] == inicial:  # si inicia la con la letra que se indica "inicial" añade el elemento a la lista de salida
      if mayuscula:             # despues no regunta si lo queremos en may o min.
        lista_out.append(element.upper())
      else:
        lista_out.append(element.lower())
  return lista_out # nos devolvera una lista, la funcion return nos devuelve el resultado

print(fun_lista(lista_W, "m", True))

lista_P = ["mercurio", "venus", "tierra", "marte", "jupiter", "saturno", "neptuno"]
print(fun_lista(lista_P, "v", True))
print(fun_lista(lista_P, "m", True))
print(fun_lista(lista_P, "s", False))

ARGUMENTOS OPCIONALES
 
Podemos asignar valores por defecto a los parametros de una funcion

In [ ]:
def fun_lista (lista, inicial, mayuscula=True): # los argumentos son los que estan en el parentesis
  lista_out = []
  for element in lista:
    if element[0] == inicial:
      if mayuscula:
        lista_out.append(element.upper())
      else:
        lista_out.append(element.lower())
  return lista_out

# Al especificar el TRUE, por default se tranforman en Mayusculas, para pasar a minusculas hay que especificar

lista_P = ["mercurio", "venus", "tierra", "marte", "jupiter", "saturno", "neptuno"]
print(fun_lista(lista_P, "m"))
print(fun_lista(lista_P, "m", True))
print(fun_lista(lista_P, "m", False))

ESPECIFICAR EL NOMBRE DE LOS ARGUMENTOS EN LA LLAMADA

Se puede especificar el nombre de los argumentos de entrada en la llamada, eliminando la necesidad de mantener su orden(su funcionamiento por default

In [ ]:
#CUANDO SON MUCHOS ARGUMENTOS ES MAS FACIL ESPECIFICAR LOS ARGUMENTOS 
lista_P = ["mercurio", "venus", "tierra", "marte", "jupiter", "saturno", "neptuno"]
print(fun_lista(inicial="v", lista=lista_P)) # ESPECIFICA LOS ARGUMENTOS

RETORNO DE MULTIPLES ELEMENTOS

El retorno de las funciones sera unico (un unico valor que se podra asignar a una variable en el codigo que invoca) seria posible devolver una secuencia y recoger los resultados en multiples variables

In [ ]:
def fun_lista (lista, inicial, mayuscula=True): 
  lista_out = []
  for element in lista:
    if element[0] == inicial:
      if mayuscula:
        lista_out.append(element.upper())
      else:
        lista_out.append(element.lower())
  return (len(lista_out), lista_out)

lista_P = ["mercurio", "venus", "tierra", "marte", "jupiter", "saturno", "neptuno"]
num_elementos, elementos = fun_lista(lista_P, "m")
for i in range(0, num_elementos):
  print(elementos[i])